version: '3'
services:
  php_data_base:
    image: mysql
    container_name: php_rest_api_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports: 
      - "3310:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      # MYSQL_DATABASE: PHPRESTAPI
      MYSQL_USER: vishva
      MYSQL_PASSWORD: admin@123
      MYSQL_ROOT_HOST: '%'
    networks:
      - web
  php_rest_api:
    container_name: php_rest_api_website
    # command: php -S 0.0.0.0:80 -t public
    build:
      context: ./
    ports:
      - 8004:80
    volumes: 
      - ./src:/var/www/html/
    depends_on:
      - php_data_base
    networks:
      - web
  # phpmyadmin
  php_data_base_access:
    depends_on:
      - php_data_base
    container_name: php_DB_Access
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8084:80'
    links: 
      - php_data_base:php_data_base
    environment:
      PMA_HOST: php_rest_api_db
      PMA_PORT: 3306
    networks:
      - web
networks:
   web: