version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    #  working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=epiz_22507512_vany
      - MYSQL_USER=vishva
      - MYSQL_PASSWORD=root
    ports:
      - "8001:3306"
    networks:
      - web
  website:
    container_name: php72
    build:
      context: ./
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=epiz_22507512_vany
      - MYSQL_USER=vishva
      - MYSQL_PASSWORD=root
    ports:
      - 8002:80
    depends_on:
      - mysql
    networks:
      - web
  admin:    
    image: adminer    
    ports:      
      - "8003:8080"
    depends_on:
      - mysql
networks:
   web: